
'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useState, useEffect } from 'react';
import Script from 'next/script';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout(
  {
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [isClient, setIsClient] = useState(false)
 
  useEffect(() => {
    setIsClient(true)
  }, []);

  return (
    
    <html lang="en" className="light" suppressHydrationWarning>
      <head>
        {/* 清除可能的緩存樣式 */}
        <meta name="theme-color" content="#ffffff" />
        <style dangerouslySetInnerHTML={{
          __html: `
            /* 強制重置主題相關樣式 */
            * { 
              color-scheme: light !important; 
            }
            html, body { 
              background: white !important; 
              color: black !important; 
            }
          `
        }} />
        
        {/* Google Tag Manager */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=AW-17686484723"></script>
        <script>
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-17686484723');
          `}
        </script>
        <Script
        src="https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserver"
        strategy="beforeInteractive"
      />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased <html lang="en" className="light bg-white text-black">`}
      >
        {isClient && children} {/* 只有在客户端加载时才渲染 children */}
      </body>
    </html>
  );
}
